# Generated by Django 5.1.1 on 2024-10-20 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TASK',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TITLE', models.CharField(max_length=150)),
                ('DESCRIPTION', models.CharField(max_length=150)),
                ('PRIORITY', models.CharField(choices=[('HIGH', 'HIGH'), ('MEDIUM', 'MEDIUM'), ('LOW', 'LOW')], max_length=200)),
                ('STATUS', models.CharField(choices=[('PENDING', 'PENDING'), ('IN-PROGRESS', 'IN-PROGRESS'), ('COMPLETED', 'COMPLETED')], max_length=150)),
            ],
        ),
    ]
