# Generated by Django 5.1.1 on 2024-10-23 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='REMARK',
            field=models.CharField(default=True, max_length=255),
        ),
    ]
